adachi.help:
  type: order
  auth: 1
  scope: 3
  headers:
    - __菜单
  enable: true
  display: true
  priority: 0
adachi.detail:
  type: order
  auth: 1
  scope: 3
  headers:
    - detail
  enable: true
  display: false
  priority: 0
adachi.call:
  type: order
  auth: 1
  scope: 3
  headers:
    - call
  enable: true
  display: true
  priority: 0
adachi.manager:
  type: switch
  auth: 3
  scope: 3
  mode: divided
  onKey: manager
  offKey: unmanaged
  header: ""
  enable: true
  display: true
  priority: 0
adachi.ban:
  type: switch
  auth: 2
  scope: 3
  mode: divided
  onKey: ban
  offKey: unban
  header: ""
  enable: true
  display: true
  priority: 0
adachi.limit:
  type: switch
  auth: 2
  scope: 3
  mode: single
  onKey: on
  offKey: off
  header: limit
  enable: true
  display: true
  priority: 0
adachi.interval:
  type: order
  auth: 2
  scope: 3
  headers:
    - int
  enable: true
  display: true
  priority: 0
adachi.hot-update-config:
  type: order
  auth: 3
  scope: 3
  headers:
    - refresh
  enable: true
  display: true
  priority: 0
adachi.hot-upgrade:
  type: order
  auth: 3
  scope: 3
  headers:
    - upgrade
  enable: true
  display: true
  priority: 0
adachi.assets:
  type: order
  auth: 3
  scope: 3
  headers:
    - assets
  enable: true
  display: true
  priority: 0
adachi.restart:
  type: order
  auth: 3
  scope: 3
  headers:
    - restart
  enable: true
  display: true
  priority: 0
adachi.reload:
  type: order
  auth: 3
  scope: 3
  headers:
    - reload
  enable: true
  display: true
  priority: 0
adachi.hot-upgrade-plugins:
  type: order
  auth: 3
  scope: 3
  headers:
    - upgrade_plugins
  enable: true
  display: true
  priority: 0
chai.searchUrl:
  type: order
  auth: 3
  scope: 3
  headers:
    - search
  enable: true
  display: true
  priority: 0
chai.searchAll:
  type: order
  auth: 1
  scope: 1
  headers:
    - __查询
    - __装备
  enable: true
  display: true
  priority: 0
chai.money:
  type: order
  auth: 1
  scope: 1
  headers:
    - __金价
  enable: true
  display: true
  priority: 0
chai.online:
  type: order
  auth: 1
  scope: 1
  headers:
    - __在线
  enable: true
  display: true
  priority: 0
chai.tips:
  type: order
  auth: 1
  scope: 1
  headers:
    - __小道消息
  enable: true
  display: true
  priority: 0
chai.strategy:
  type: order
  auth: 1
  scope: 1
  headers:
    - __悬赏
  enable: true
  display: true
  priority: 0
chai.grown:
  type: order
  auth: 1
  scope: 1
  headers:
    - __材料
  enable: true
  display: true
  priority: 0
chai.oldMoney:
  type: order
  auth: 1
  scope: 1
  headers:
    - __怀旧金价
  enable: true
  display: true
  priority: 0
chai.entry:
  type: order
  auth: 1
  scope: 1
  headers:
    - __词条
  enable: true
  display: true
  priority: 0
chai.outSide:
  type: order
  auth: 1
  scope: 1
  headers:
    - __野外
  enable: true
  display: true
  priority: 0
chai.timetips:
  type: order
  auth: 1
  scope: 1
  headers:
    - __怀旧服小道消息
  enable: true
  display: true
  priority: 0
chai.weather:
  type: order
  auth: 1
  scope: 1
  headers:
    - __天气
  enable: true
  display: true
  priority: 0
chai.rubbish:
  type: order
  auth: 1
  scope: 1
  headers:
    - __分类
  enable: true
  display: true
  priority: 0
chai.gas:
  type: order
  auth: 1
  scope: 1
  headers:
    - __油价
  enable: true
  display: true
  priority: 0
chai.role:
  type: order
  auth: 1
  scope: 1
  headers:
    - __路况
  enable: true
  display: true
  priority: 0
chai.news:
  type: order
  auth: 1
  scope: 1
  headers:
    - __新闻
  enable: true
  display: true
  priority: 0
chai.fish:
  type: order
  auth: 1
  scope: 1
  headers:
    - __摸鱼
  enable: true
  display: true
  priority: 0
chai.lucky:
  type: order
  auth: 1
  scope: 1
  headers:
    - __今日运势
    - 今日运势
  enable: true
  display: true
  priority: 0
chai.happy:
  type: order
  auth: 1
  scope: 1
  headers:
    - __喜报
  enable: true
  display: true
  priority: 0
chai.speak:
  type: order
  auth: 1
  scope: 3
  headers:
    - __群友说
  enable: true
  display: true
  priority: 0
chai.soup:
  type: order
  auth: 1
  scope: 3
  headers:
    - __毒鸡汤
  enable: true
  display: true
  priority: 0
chai.dog:
  type: order
  auth: 1
  scope: 3
  headers:
    - __舔狗日记
  enable: true
  display: true
  priority: 0
chai.mind:
  type: order
  auth: 1
  scope: 1
  headers:
    - __发病
  enable: true
  display: true
  priority: 0
chai.bite:
  type: order
  auth: 1
  scope: 1
  headers:
    - __咬
  enable: true
  display: true
  priority: 0
chai.tip:
  type: order
  auth: 1
  scope: 1
  headers:
    - __顶
  enable: true
  display: true
  priority: 0
chai.hug:
  type: order
  auth: 1
  scope: 1
  headers:
    - __抱
  enable: true
  display: true
  priority: 0
chai.hit:
  type: order
  auth: 1
  scope: 1
  headers:
    - __锤
  enable: true
  display: true
  priority: 0
chai.look:
  type: order
  auth: 1
  scope: 1
  headers:
    - __指
  enable: true
  display: true
  priority: 0
chai.beat:
  type: order
  auth: 1
  scope: 1
  headers:
    - __拍
  enable: true
  display: true
  priority: 0
chai.grab:
  type: order
  auth: 1
  scope: 1
  headers:
    - __抓
  enable: true
  display: true
  priority: 0
tools.dice:
  type: order
  auth: 1
  scope: 3
  headers:
    - dice
  enable: true
  display: true
  priority: 0
